// Code generated by "stringer -type=Argon2ErrorType"; DO NOT EDIT.

package passwords

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Argon2InvalidHash-0]
	_ = x[Argon2UnsupportedAlgorithm-1]
}

const _Argon2ErrorType_name = "Argon2InvalidHashArgon2UnsupportedAlgorithm"

var _Argon2ErrorType_index = [...]uint8{0, 17, 43}

func (i Argon2ErrorType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Argon2ErrorType_index)-1 {
		return "Argon2ErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Argon2ErrorType_name[_Argon2ErrorType_index[idx]:_Argon2ErrorType_index[idx+1]]
}
