// Code generated by "stringer -type=ActionPermission -trimprefix=Permission"; DO NOT EDIT.

package permissions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PermissionUnknownAction-0]
	_ = x[PermissionPlusOne-1]
	_ = x[PermissionSoftVeto-2]
	_ = x[PermissionHardVeto-3]
	_ = x[PermissionView-4]
	_ = x[PermissionSubmit-5]
	_ = x[PermissionWrite-6]
}

const _ActionPermission_name = "UnknownActionPlusOneSoftVetoHardVetoViewSubmitWrite"

var _ActionPermission_index = [...]uint8{0, 13, 20, 28, 36, 40, 46, 51}

func (i ActionPermission) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ActionPermission_index)-1 {
		return "ActionPermission(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionPermission_name[_ActionPermission_index[idx]:_ActionPermission_index[idx+1]]
}
