// Code generated by "stringer -type=ActionPermission -trimprefix=Permission"; DO NOT EDIT.

package permissions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PermissionPlusOne-0]
	_ = x[PermissionSoftVeto-1]
	_ = x[PermissionHardVeto-2]
	_ = x[PermissionView-3]
	_ = x[PermissionSubmit-4]
	_ = x[PermissionWrite-5]
	_ = x[PermissionUnknownAction-6]
}

const _ActionPermission_name = "PlusOneSoftVetoHardVetoViewSubmitWriteUnknownAction"

var _ActionPermission_index = [...]uint8{0, 7, 15, 23, 27, 33, 38, 51}

func (i ActionPermission) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ActionPermission_index)-1 {
		return "ActionPermission(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionPermission_name[_ActionPermission_index[idx]:_ActionPermission_index[idx+1]]
}
