// Code generated by "stringer -type=PermissionConfigErrorType -trimprefix=Permission"; DO NOT EDIT.

package permissions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PermissionConfigErrorInvalidString-0]
	_ = x[PermissionConfigErrorInvalidPermissionSet-1]
	_ = x[PermissionConfigErrorInvalidAction-2]
}

const _PermissionConfigErrorType_name = "ConfigErrorInvalidStringConfigErrorInvalidPermissionSetConfigErrorInvalidAction"

var _PermissionConfigErrorType_index = [...]uint8{0, 24, 55, 79}

func (i PermissionConfigErrorType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PermissionConfigErrorType_index)-1 {
		return "PermissionConfigErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PermissionConfigErrorType_name[_PermissionConfigErrorType_index[idx]:_PermissionConfigErrorType_index[idx+1]]
}
