// Code generated by "stringer -type=LogLevel"; DO NOT EDIT.

package logger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogLevelInfo-0]
	_ = x[LogLevelDebug-1]
	_ = x[LogLevelError-2]
}

const _LogLevel_name = "LogLevelInfoLogLevelDebugLogLevelError"

var _LogLevel_index = [...]uint8{0, 12, 25, 38}

func (i LogLevel) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LogLevel_index)-1 {
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[idx]:_LogLevel_index[idx+1]]
}
