// Code generated by "stringer -type=ArtifactFileType"; DO NOT EDIT.

package artifactmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArtifactUnknown-0]
	_ = x[ArtifactPNG-1]
	_ = x[ArtifactJPG-2]
}

const _ArtifactFileType_name = "ArtifactUnknownArtifactPNGArtifactJPG"

var _ArtifactFileType_index = [...]uint8{0, 15, 26, 37}

func (i ArtifactFileType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ArtifactFileType_index)-1 {
		return "ArtifactFileType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArtifactFileType_name[_ArtifactFileType_index[idx]:_ArtifactFileType_index[idx+1]]
}
