// Code generated by "stringer -type=ConfigErrorType -trimprefix=Config"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConfigErrorOpenFile-0]
	_ = x[ConfigErrorAtoiError-1]
	_ = x[ConfigErrorDecodeError-2]
	_ = x[ConfigErrorInvaidFormatting-3]
}

const _ConfigErrorType_name = "ErrorOpenFileErrorAtoiErrorErrorDecodeErrorErrorInvaidFormatting"

var _ConfigErrorType_index = [...]uint8{0, 13, 27, 43, 64}

func (i ConfigErrorType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ConfigErrorType_index)-1 {
		return "ConfigErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConfigErrorType_name[_ConfigErrorType_index[idx]:_ConfigErrorType_index[idx+1]]
}
