// Code generated by "stringer -type=DeadlineParsingErrorType -trimprefix=ConfigParsing"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConfigParsingErrorUnexpectedLengthSpecifier-0]
	_ = x[ConfigParsingErrorAtoiError-1]
}

const _DeadlineParsingErrorType_name = "ErrorUnexpectedLengthSpecifierErrorAtoiError"

var _DeadlineParsingErrorType_index = [...]uint8{0, 30, 44}

func (i DeadlineParsingErrorType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DeadlineParsingErrorType_index)-1 {
		return "DeadlineParsingErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeadlineParsingErrorType_name[_DeadlineParsingErrorType_index[idx]:_DeadlineParsingErrorType_index[idx+1]]
}
