// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   int32
	Name string
}

type Permission struct {
	ID      int32
	Action  string
	Context string
}

type Pipeline struct {
	ID          int64
	Name        string
	Version     []byte
	Description pgtype.Text
}

type PipelineStage struct {
	PipelineID int64
	StageID    int64
	Position   int32
}

type Role struct {
	ID   int32
	Name string
}

type RolePermission struct {
	RoleID       int32
	PermissionID int32
}

type Section struct {
	ID       int32
	Name     string
	Category pgtype.Int4
}

type SectionPipeline struct {
	SectionID  int32
	PipelineID int32
}

type Stage struct {
	ID              int64
	Name            string
	Version         []byte
	PlusOneRequired int16
	Blind           bool
	SoftVeto        bool
	HasDeadline     bool
	DeadlineStr     pgtype.Text
}

type User struct {
	ID         int64
	Name       string
	InternalID pgtype.Text
	Password   string
	Email      pgtype.Text
}

type UserRole struct {
	UserID int64
	RoleID int32
}
