// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission.sql

package db

import (
	"context"
)

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions WHERE context = $1 AND action = $2
`

type DeletePermissionParams struct {
	Context string
	Action  string
}

func (q *Queries) DeletePermission(ctx context.Context, arg DeletePermissionParams) error {
	_, err := q.db.Exec(ctx, deletePermission, arg.Context, arg.Action)
	return err
}

const deletePermissionContext = `-- name: DeletePermissionContext :exec
DELETE FROM permissions WHERE context = $1
`

func (q *Queries) DeletePermissionContext(ctx context.Context, argContext string) error {
	_, err := q.db.Exec(ctx, deletePermissionContext, argContext)
	return err
}

const getPermissionByContext = `-- name: GetPermissionByContext :many
SELECT action FROM permissions WHERE context = $1 LIMIT 1
`

func (q *Queries) GetPermissionByContext(ctx context.Context, argContext string) ([]string, error) {
	rows, err := q.db.Query(ctx, getPermissionByContext, argContext)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var action string
		if err := rows.Scan(&action); err != nil {
			return nil, err
		}
		items = append(items, action)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionId = `-- name: GetPermissionId :one
SELECT id FROM permissions WHERE context = $1 AND action = $2
`

type GetPermissionIdParams struct {
	Context string
	Action  string
}

func (q *Queries) GetPermissionId(ctx context.Context, arg GetPermissionIdParams) (int32, error) {
	row := q.db.QueryRow(ctx, getPermissionId, arg.Context, arg.Action)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertPermission = `-- name: InsertPermission :exec
INSERT INTO permissions (action, context)
VALUES ($1, $2)
`

type InsertPermissionParams struct {
	Action  string
	Context string
}

func (q *Queries) InsertPermission(ctx context.Context, arg InsertPermissionParams) error {
	_, err := q.db.Exec(ctx, insertPermission, arg.Action, arg.Context)
	return err
}
