// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipelines.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPipelineByVersion = `-- name: GetPipelineByVersion :one
SELECT id, name, version, description FROM pipelines
WHERE version = $1
`

func (q *Queries) GetPipelineByVersion(ctx context.Context, version []byte) (Pipeline, error) {
	row := q.db.QueryRow(ctx, getPipelineByVersion, version)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
	)
	return i, err
}

const getPipelineStages = `-- name: GetPipelineStages :many
SELECT s.id, s.name, s.version, s.plus_one_required, s.blind, s.soft_veto, s.has_deadline, s.deadline_str
FROM pipeline_stages ps
JOIN stages s
    ON s.id = ps.stage_id
WHERE ps.pipeline_id = $1
ORDER BY ps.position
`

func (q *Queries) GetPipelineStages(ctx context.Context, pipelineID int64) ([]Stage, error) {
	rows, err := q.db.Query(ctx, getPipelineStages, pipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stage
	for rows.Next() {
		var i Stage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.PlusOneRequired,
			&i.Blind,
			&i.SoftVeto,
			&i.HasDeadline,
			&i.DeadlineStr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStageByVersion = `-- name: GetStageByVersion :one
SELECT id, name, version, plus_one_required, blind, soft_veto, has_deadline, deadline_str FROM stages
WHERE version = $1
`

func (q *Queries) GetStageByVersion(ctx context.Context, version []byte) (Stage, error) {
	row := q.db.QueryRow(ctx, getStageByVersion, version)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.PlusOneRequired,
		&i.Blind,
		&i.SoftVeto,
		&i.HasDeadline,
		&i.DeadlineStr,
	)
	return i, err
}

const insertPipeline = `-- name: InsertPipeline :one
INSERT INTO pipelines (
    name,
    version,
    description
)
VALUES ($1,$2,$3)
RETURNING id, name, version, description
`

type InsertPipelineParams struct {
	Name        string
	Version     []byte
	Description pgtype.Text
}

func (q *Queries) InsertPipeline(ctx context.Context, arg InsertPipelineParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, insertPipeline, arg.Name, arg.Version, arg.Description)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
	)
	return i, err
}

const insertPipelineStage = `-- name: InsertPipelineStage :exec
INSERT INTO pipeline_stages (
    pipeline_id,
    stage_id,
    position
)
VALUES ($1,$2,$3)
`

type InsertPipelineStageParams struct {
	PipelineID int64
	StageID    int64
	Position   int32
}

func (q *Queries) InsertPipelineStage(ctx context.Context, arg InsertPipelineStageParams) error {
	_, err := q.db.Exec(ctx, insertPipelineStage, arg.PipelineID, arg.StageID, arg.Position)
	return err
}

const insertStage = `-- name: InsertStage :one
INSERT INTO stages (
    name,
    version,
    plus_one_required,
    blind,
    soft_veto,
    has_deadline,
    deadline_str
)
VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, name, version, plus_one_required, blind, soft_veto, has_deadline, deadline_str
`

type InsertStageParams struct {
	Name            string
	Version         []byte
	PlusOneRequired int16
	Blind           bool
	SoftVeto        bool
	HasDeadline     bool
	DeadlineStr     pgtype.Text
}

func (q *Queries) InsertStage(ctx context.Context, arg InsertStageParams) (Stage, error) {
	row := q.db.QueryRow(ctx, insertStage,
		arg.Name,
		arg.Version,
		arg.PlusOneRequired,
		arg.Blind,
		arg.SoftVeto,
		arg.HasDeadline,
		arg.DeadlineStr,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.PlusOneRequired,
		&i.Blind,
		&i.SoftVeto,
		&i.HasDeadline,
		&i.DeadlineStr,
	)
	return i, err
}
