// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipelines.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePipelineById = `-- name: DeletePipelineById :exec
DELETE FROM pipelines
WHERE id = $1
`

func (q *Queries) DeletePipelineById(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePipelineById, id)
	return err
}

const getHowManyUseByPipelineId = `-- name: GetHowManyUseByPipelineId :one
SELECT COUNT(s.id)
FROM submissions s
JOIN pipelines p
    ON s.pipeline = p.id
WHERE p.id = $1
`

func (q *Queries) GetHowManyUseByPipelineId(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getHowManyUseByPipelineId, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPipelineByVersion = `-- name: GetPipelineByVersion :one
SELECT id, name, version, description FROM pipelines
WHERE version = $1
`

func (q *Queries) GetPipelineByVersion(ctx context.Context, version []byte) (Pipeline, error) {
	row := q.db.QueryRow(ctx, getPipelineByVersion, version)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
	)
	return i, err
}

const getPipelineStage = `-- name: GetPipelineStage :one
SELECT id, pipeline_id, stage_id, position FROM pipeline_stages
WHERE pipeline_id = $1 AND position = $2
`

type GetPipelineStageParams struct {
	PipelineID int64
	Position   int32
}

func (q *Queries) GetPipelineStage(ctx context.Context, arg GetPipelineStageParams) (PipelineStage, error) {
	row := q.db.QueryRow(ctx, getPipelineStage, arg.PipelineID, arg.Position)
	var i PipelineStage
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.StageID,
		&i.Position,
	)
	return i, err
}

const getPipelineStages = `-- name: GetPipelineStages :many
SELECT s.id, s.name, s.version, s.plus_one_required, s.blind, s.soft_veto, s.has_deadline, s.deadline_str, s.final
FROM pipeline_stages ps
JOIN stages s
    ON s.id = ps.stage_id
WHERE ps.pipeline_id = $1
ORDER BY ps.position
`

func (q *Queries) GetPipelineStages(ctx context.Context, pipelineID int64) ([]Stage, error) {
	rows, err := q.db.Query(ctx, getPipelineStages, pipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stage
	for rows.Next() {
		var i Stage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.PlusOneRequired,
			&i.Blind,
			&i.SoftVeto,
			&i.HasDeadline,
			&i.DeadlineStr,
			&i.Final,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPipelinesIds = `-- name: GetPipelinesIds :many
SELECT id FROM pipelines
`

func (q *Queries) GetPipelinesIds(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, getPipelinesIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStageById = `-- name: GetStageById :one
SELECT id, name, version, plus_one_required, blind, soft_veto, has_deadline, deadline_str, final FROM stages
WHERE id = $1
`

func (q *Queries) GetStageById(ctx context.Context, id int64) (Stage, error) {
	row := q.db.QueryRow(ctx, getStageById, id)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.PlusOneRequired,
		&i.Blind,
		&i.SoftVeto,
		&i.HasDeadline,
		&i.DeadlineStr,
		&i.Final,
	)
	return i, err
}

const getStageByVersion = `-- name: GetStageByVersion :one
SELECT id, name, version, plus_one_required, blind, soft_veto, has_deadline, deadline_str, final FROM stages
WHERE version = $1
`

func (q *Queries) GetStageByVersion(ctx context.Context, version []byte) (Stage, error) {
	row := q.db.QueryRow(ctx, getStageByVersion, version)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.PlusOneRequired,
		&i.Blind,
		&i.SoftVeto,
		&i.HasDeadline,
		&i.DeadlineStr,
		&i.Final,
	)
	return i, err
}

const insertPipeline = `-- name: InsertPipeline :one
INSERT INTO pipelines (
    name,
    version,
    description
)
VALUES ($1,$2,$3)
RETURNING id, name, version, description
`

type InsertPipelineParams struct {
	Name        string
	Version     []byte
	Description pgtype.Text
}

func (q *Queries) InsertPipeline(ctx context.Context, arg InsertPipelineParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, insertPipeline, arg.Name, arg.Version, arg.Description)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
	)
	return i, err
}

const insertPipelineStage = `-- name: InsertPipelineStage :exec
INSERT INTO pipeline_stages (
    pipeline_id,
    stage_id,
    position
)
VALUES ($1,$2,$3)
`

type InsertPipelineStageParams struct {
	PipelineID int64
	StageID    int64
	Position   int32
}

func (q *Queries) InsertPipelineStage(ctx context.Context, arg InsertPipelineStageParams) error {
	_, err := q.db.Exec(ctx, insertPipelineStage, arg.PipelineID, arg.StageID, arg.Position)
	return err
}

const insertStage = `-- name: InsertStage :one
INSERT INTO stages (
    name,
    version,
    plus_one_required,
    blind,
    soft_veto,
    has_deadline,
    deadline_str,
    final
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, name, version, plus_one_required, blind, soft_veto, has_deadline, deadline_str, final
`

type InsertStageParams struct {
	Name            string
	Version         []byte
	PlusOneRequired int16
	Blind           bool
	SoftVeto        bool
	HasDeadline     bool
	DeadlineStr     pgtype.Text
	Final           bool
}

func (q *Queries) InsertStage(ctx context.Context, arg InsertStageParams) (Stage, error) {
	row := q.db.QueryRow(ctx, insertStage,
		arg.Name,
		arg.Version,
		arg.PlusOneRequired,
		arg.Blind,
		arg.SoftVeto,
		arg.HasDeadline,
		arg.DeadlineStr,
		arg.Final,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.PlusOneRequired,
		&i.Blind,
		&i.SoftVeto,
		&i.HasDeadline,
		&i.DeadlineStr,
		&i.Final,
	)
	return i, err
}
