// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPermissionToRole = `-- name: AddPermissionToRole :exec
insert into role_permissions (role_id, permission_id)
values ($1, $2)
`

type AddPermissionToRoleParams struct {
	RoleID       int32
	PermissionID int32
}

func (q *Queries) AddPermissionToRole(ctx context.Context, arg AddPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, addPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const addUserToRole = `-- name: AddUserToRole :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
`

type AddUserToRoleParams struct {
	UserID int64
	RoleID int32
}

func (q *Queries) AddUserToRole(ctx context.Context, arg AddUserToRoleParams) error {
	_, err := q.db.Exec(ctx, addUserToRole, arg.UserID, arg.RoleID)
	return err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions WHERE context = $1 AND action = $2
`

type DeletePermissionParams struct {
	Context string
	Action  string
}

func (q *Queries) DeletePermission(ctx context.Context, arg DeletePermissionParams) error {
	_, err := q.db.Exec(ctx, deletePermission, arg.Context, arg.Action)
	return err
}

const deletePermissionContext = `-- name: DeletePermissionContext :exec
DELETE FROM permissions WHERE context = $1
`

func (q *Queries) DeletePermissionContext(ctx context.Context, argContext string) error {
	_, err := q.db.Exec(ctx, deletePermissionContext, argContext)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getBasicInfoByEmail = `-- name: GetBasicInfoByEmail :one
SELECT password, id, name FROM users
WHERE email = $1 LIMIT 1
`

type GetBasicInfoByEmailRow struct {
	Password string
	ID       int64
	Name     string
}

func (q *Queries) GetBasicInfoByEmail(ctx context.Context, email pgtype.Text) (GetBasicInfoByEmailRow, error) {
	row := q.db.QueryRow(ctx, getBasicInfoByEmail, email)
	var i GetBasicInfoByEmailRow
	err := row.Scan(&i.Password, &i.ID, &i.Name)
	return i, err
}

const getBasicInfoByUserName = `-- name: GetBasicInfoByUserName :one
SELECT password, id, name FROM users
WHERE name = $1 LIMIT 1
`

type GetBasicInfoByUserNameRow struct {
	Password string
	ID       int64
	Name     string
}

func (q *Queries) GetBasicInfoByUserName(ctx context.Context, name string) (GetBasicInfoByUserNameRow, error) {
	row := q.db.QueryRow(ctx, getBasicInfoByUserName, name)
	var i GetBasicInfoByUserNameRow
	err := row.Scan(&i.Password, &i.ID, &i.Name)
	return i, err
}

const getPermissionByContext = `-- name: GetPermissionByContext :many
SELECT action FROM permissions WHERE context = $1 LIMIT 1
`

func (q *Queries) GetPermissionByContext(ctx context.Context, argContext string) ([]string, error) {
	rows, err := q.db.Query(ctx, getPermissionByContext, argContext)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var action string
		if err := rows.Scan(&action); err != nil {
			return nil, err
		}
		items = append(items, action)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionId = `-- name: GetPermissionId :one
SELECT id FROM permissions WHERE context = $1 AND action = $2
`

type GetPermissionIdParams struct {
	Context string
	Action  string
}

func (q *Queries) GetPermissionId(ctx context.Context, arg GetPermissionIdParams) (int32, error) {
	row := q.db.QueryRow(ctx, getPermissionId, arg.Context, arg.Action)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name FROM roles
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT p.id, p.action, p.context FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
`

func (q *Queries) GetRolePermissions(ctx context.Context, roleID int32) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Action, &i.Context); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, internal_id, password, email FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InternalID,
		&i.Password,
		&i.Email,
	)
	return i, err
}

const getUserByInternalId = `-- name: GetUserByInternalId :one
SELECT id, name, internal_id, password, email FROM users
WHERE internal_id = $1 LIMIT 1
`

func (q *Queries) GetUserByInternalId(ctx context.Context, internalID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByInternalId, internalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InternalID,
		&i.Password,
		&i.Email,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, internal_id, password, email FROM users
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InternalID,
		&i.Password,
		&i.Email,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT DISTINCT p.id, p.action, p.context
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN user_roles ur ON ur.role_id = rp.role_id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserPermissions(ctx context.Context, userID int64) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Action, &i.Context); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.name FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID int64) ([]Role, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPermission = `-- name: InsertPermission :exec
INSERT INTO permissions (action, context)
VALUES ($1, $2)
`

type InsertPermissionParams struct {
	Action  string
	Context string
}

func (q *Queries) InsertPermission(ctx context.Context, arg InsertPermissionParams) error {
	_, err := q.db.Exec(ctx, insertPermission, arg.Action, arg.Context)
	return err
}

const insertRole = `-- name: InsertRole :exec
INSERT INTO roles (name)
VALUES ($1) RETURNING id, name
`

func (q *Queries) InsertRole(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, insertRole, name)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (
  name, internal_id, password, email
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, internal_id, password, email
`

type InsertUserParams struct {
	Name       string
	InternalID pgtype.Text
	Password   string
	Email      pgtype.Text
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.Name,
		arg.InternalID,
		arg.Password,
		arg.Email,
	)
	return err
}

const removePermissionFromRole = `-- name: RemovePermissionFromRole :exec
DELETE FROM role_permissions
WHERE role_id = $1 AND permission_id = $2
`

type RemovePermissionFromRoleParams struct {
	RoleID       int32
	PermissionID int32
}

func (q *Queries) RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, removePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}
