// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddPermissionToRole(ctx context.Context, arg AddPermissionToRoleParams) error
	AddPlusOne(ctx context.Context, arg AddPlusOneParams) error
	AddUserToRole(ctx context.Context, arg AddUserToRoleParams) error
	CountPlusOnes(ctx context.Context, submissionID int64) (int64, error)
	DeleteArtifact(ctx context.Context, arg DeleteArtifactParams) error
	DeleteArtifactByGen(ctx context.Context, arg DeleteArtifactByGenParams) error
	DeletePermission(ctx context.Context, arg DeletePermissionParams) error
	DeletePermissionContext(ctx context.Context, argContext string) error
	DeletePipelineById(ctx context.Context, id int64) error
	DeletePlusOne(ctx context.Context, arg DeletePlusOneParams) error
	DeleteRoleByName(ctx context.Context, name string) error
	DeleteUser(ctx context.Context, id int64) error
	ExistsArtifact(ctx context.Context, arg ExistsArtifactParams) (bool, error)
	ExistsArtifactRev(ctx context.Context, arg ExistsArtifactRevParams) (bool, error)
	GetArtifactByGeneration(ctx context.Context, arg GetArtifactByGenerationParams) (SubmissionArtifact, error)
	GetArtifacts(ctx context.Context, arg GetArtifactsParams) ([]SubmissionArtifact, error)
	GetArtifactsBySubmission(ctx context.Context, arg GetArtifactsBySubmissionParams) ([]SubmissionArtifact, error)
	GetBasicInfoByEmail(ctx context.Context, email pgtype.Text) (GetBasicInfoByEmailRow, error)
	GetBasicInfoByUserName(ctx context.Context, name string) (GetBasicInfoByUserNameRow, error)
	GetHowManyUseByPipelineId(ctx context.Context, id int64) (int64, error)
	GetNewestArtifact(ctx context.Context, arg GetNewestArtifactParams) (SubmissionArtifact, error)
	GetPermissionByContext(ctx context.Context, argContext string) ([]string, error)
	GetPermissionId(ctx context.Context, arg GetPermissionIdParams) (int32, error)
	GetPipelineByVersion(ctx context.Context, version []byte) (Pipeline, error)
	GetPipelineStages(ctx context.Context, pipelineID int64) ([]Stage, error)
	GetPipelinesIds(ctx context.Context) ([]int64, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetRoleNames(ctx context.Context) ([]string, error)
	GetRolePermissions(ctx context.Context, roleID int32) ([]Permission, error)
	GetStageByVersion(ctx context.Context, version []byte) (Stage, error)
	GetSubmissionsByAuthor(ctx context.Context, author int64) ([]Submission, error)
	GetSubmissionsByAuthorOffset(ctx context.Context, arg GetSubmissionsByAuthorOffsetParams) ([]Submission, error)
	GetSubmissionsByHash(ctx context.Context, hash string) (Submission, error)
	GetSubmissionsById(ctx context.Context, id int64) (Submission, error)
	GetUnusedPipelines(ctx context.Context) ([]Pipeline, error)
	GetUnusedRoles(ctx context.Context) ([]Role, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserByInternalId(ctx context.Context, internalID pgtype.Text) (User, error)
	GetUserByName(ctx context.Context, name string) (User, error)
	GetUserPermissions(ctx context.Context, userID int64) ([]Permission, error)
	GetUserRoles(ctx context.Context, userID int64) ([]Role, error)
	InsertArtifact(ctx context.Context, arg InsertArtifactParams) error
	InsertPermission(ctx context.Context, arg InsertPermissionParams) error
	InsertPipeline(ctx context.Context, arg InsertPipelineParams) (Pipeline, error)
	InsertPipelineStage(ctx context.Context, arg InsertPipelineStageParams) error
	InsertRole(ctx context.Context, name string) error
	InsertStage(ctx context.Context, arg InsertStageParams) (Stage, error)
	InsertSubmission(ctx context.Context, arg InsertSubmissionParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error
	ResetPlusOneForSubmission(ctx context.Context, submissionID int64) error
}

var _ Querier = (*Queries)(nil)
