// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role.sql

package db

import (
	"context"
)

const addPermissionToRole = `-- name: AddPermissionToRole :exec
insert into role_permissions (role_id, permission_id)
values ($1, $2)
`

type AddPermissionToRoleParams struct {
	RoleID       int32
	PermissionID int32
}

func (q *Queries) AddPermissionToRole(ctx context.Context, arg AddPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, addPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const addUserToRole = `-- name: AddUserToRole :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
`

type AddUserToRoleParams struct {
	UserID int64
	RoleID int32
}

func (q *Queries) AddUserToRole(ctx context.Context, arg AddUserToRoleParams) error {
	_, err := q.db.Exec(ctx, addUserToRole, arg.UserID, arg.RoleID)
	return err
}

const deleteRoleByName = `-- name: DeleteRoleByName :exec
DELETE FROM roles
WHERE name = $1
`

func (q *Queries) DeleteRoleByName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteRoleByName, name)
	return err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name FROM roles
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getRoleNames = `-- name: GetRoleNames :many
SELECT name FROM roles
`

func (q *Queries) GetRoleNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getRoleNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT p.id, p.action, p.context FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
`

func (q *Queries) GetRolePermissions(ctx context.Context, roleID int32) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Action, &i.Context); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRole = `-- name: InsertRole :exec
INSERT INTO roles (name)
VALUES ($1) RETURNING id, name
`

func (q *Queries) InsertRole(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, insertRole, name)
	return err
}

const removePermissionFromRole = `-- name: RemovePermissionFromRole :exec
DELETE FROM role_permissions
WHERE role_id = $1 AND permission_id = $2
`

type RemovePermissionFromRoleParams struct {
	RoleID       int32
	PermissionID int32
}

func (q *Queries) RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, removePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}
