// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlusOne = `-- name: AddPlusOne :exec
INSERT INTO plus_ones (user_id, submission_id)
VALUES ($1, $2)
`

type AddPlusOneParams struct {
	UserID       int64
	SubmissionID int64
}

func (q *Queries) AddPlusOne(ctx context.Context, arg AddPlusOneParams) error {
	_, err := q.db.Exec(ctx, addPlusOne, arg.UserID, arg.SubmissionID)
	return err
}

const countPlusOnes = `-- name: CountPlusOnes :one
SELECT COUNT(*) FROM plus_ones
WHERE submission_id = $1
`

func (q *Queries) CountPlusOnes(ctx context.Context, submissionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPlusOnes, submissionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePlusOne = `-- name: DeletePlusOne :exec
DELETE FROM plus_ones WHERE user_id = $1 AND submission_id = $2
`

type DeletePlusOneParams struct {
	UserID       int64
	SubmissionID int64
}

func (q *Queries) DeletePlusOne(ctx context.Context, arg DeletePlusOneParams) error {
	_, err := q.db.Exec(ctx, deletePlusOne, arg.UserID, arg.SubmissionID)
	return err
}

const getSubmissionsByAuthor = `-- name: GetSubmissionsByAuthor :many
SELECT id, created_at, content, author, hash FROM submissions
WHERE author = $1
`

func (q *Queries) GetSubmissionsByAuthor(ctx context.Context, author int64) ([]Submission, error) {
	rows, err := q.db.Query(ctx, getSubmissionsByAuthor, author)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Content,
			&i.Author,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubmissionsByHash = `-- name: GetSubmissionsByHash :one
SELECT id, created_at, content, author, hash FROM submissions
WHERE hash = $1
`

func (q *Queries) GetSubmissionsByHash(ctx context.Context, hash string) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionsByHash, hash)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Content,
		&i.Author,
		&i.Hash,
	)
	return i, err
}

const getSubmissionsById = `-- name: GetSubmissionsById :one
SELECT id, created_at, content, author, hash FROM submissions
WHERE id = $1
`

func (q *Queries) GetSubmissionsById(ctx context.Context, id int64) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionsById, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Content,
		&i.Author,
		&i.Hash,
	)
	return i, err
}

const getUnusedPipelines = `-- name: GetUnusedPipelines :many
SELECT p.id, p.name, p.version, p.description
FROM pipelines p
WHERE NOT EXISTS (
    SELECT 1
    FROM submissions s
    WHERE s.pipeline_id = p.id
)
`

func (q *Queries) GetUnusedPipelines(ctx context.Context) ([]Pipeline, error) {
	rows, err := q.db.Query(ctx, getUnusedPipelines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pipeline
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSubmission = `-- name: InsertSubmission :exec
INSERT INTO submissions (content, author, hash)
VALUES ($1, $2, $3)
`

type InsertSubmissionParams struct {
	Content pgtype.Text
	Author  int64
	Hash    string
}

func (q *Queries) InsertSubmission(ctx context.Context, arg InsertSubmissionParams) error {
	_, err := q.db.Exec(ctx, insertSubmission, arg.Content, arg.Author, arg.Hash)
	return err
}

const resetPlusOneForSubmission = `-- name: ResetPlusOneForSubmission :exec
DELETE FROM plus_ones WHERE submission_id = $1
`

func (q *Queries) ResetPlusOneForSubmission(ctx context.Context, submissionID int64) error {
	_, err := q.db.Exec(ctx, resetPlusOneForSubmission, submissionID)
	return err
}
