// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getBasicInfoByEmail = `-- name: GetBasicInfoByEmail :one
SELECT password, id, name FROM users
WHERE email = $1 LIMIT 1
`

type GetBasicInfoByEmailRow struct {
	Password string
	ID       int64
	Name     string
}

func (q *Queries) GetBasicInfoByEmail(ctx context.Context, email pgtype.Text) (GetBasicInfoByEmailRow, error) {
	row := q.db.QueryRow(ctx, getBasicInfoByEmail, email)
	var i GetBasicInfoByEmailRow
	err := row.Scan(&i.Password, &i.ID, &i.Name)
	return i, err
}

const getBasicInfoByUserName = `-- name: GetBasicInfoByUserName :one
SELECT password, id, name FROM users
WHERE name = $1 LIMIT 1
`

type GetBasicInfoByUserNameRow struct {
	Password string
	ID       int64
	Name     string
}

func (q *Queries) GetBasicInfoByUserName(ctx context.Context, name string) (GetBasicInfoByUserNameRow, error) {
	row := q.db.QueryRow(ctx, getBasicInfoByUserName, name)
	var i GetBasicInfoByUserNameRow
	err := row.Scan(&i.Password, &i.ID, &i.Name)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, internal_id, password, email FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InternalID,
		&i.Password,
		&i.Email,
	)
	return i, err
}

const getUserByInternalId = `-- name: GetUserByInternalId :one
SELECT id, name, internal_id, password, email FROM users
WHERE internal_id = $1 LIMIT 1
`

func (q *Queries) GetUserByInternalId(ctx context.Context, internalID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByInternalId, internalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InternalID,
		&i.Password,
		&i.Email,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, internal_id, password, email FROM users
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InternalID,
		&i.Password,
		&i.Email,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT DISTINCT p.id, p.action, p.context
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN user_roles ur ON ur.role_id = rp.role_id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserPermissions(ctx context.Context, userID int64) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Action, &i.Context); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.name FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID int64) ([]Role, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (
  name, internal_id, password, email
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, internal_id, password, email
`

type InsertUserParams struct {
	Name       string
	InternalID pgtype.Text
	Password   string
	Email      pgtype.Text
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.Name,
		arg.InternalID,
		arg.Password,
		arg.Email,
	)
	return err
}
